### ISSUE TITLE
Power label mV instead of mW

### ISSUE THREAD

**Issue by ajay10000** [KarlTorp/Tiny-VA-Meter#2]
I know this is a few years old, but...  Thanks for the great work!  The menu settings are a really nice option and the different screens are well done.  I've just got it to compile on the ESP8266 in PlatformIO and added the option of sending the values to MQTT via WiFi.

Just a small issue, line 419 in the print_four_lines output for the OLED display, the label for Power is mV and should be mW.
i.e. `parseFloatTextWithUnit(power_mW, 2, " mW").c_str()`.  This doesn't affect the operation of the program.

Also, the labels for the touch sensitive switch supply polarity appear to be reversed between the schematic drawing and the 'picture schematic'.  I was a bit confused when trying to work out which way the capacitive switch was pulling the data line.

I had some trouble with a normal push button press not being recognised, however changing `#define BUTTON_PRESSED_STATE HIGH` to `#define BUTTON_PRESSED_STATE LOW` and grounding the data line with the switch instead of pulling it up worked a treat (on the ESP).

Thanks again - Andrew

**Comment by KarlTorp** [comment]
Hi Andrew!

Sorry about the late reply, I didn't receive any notification on this so I happened to see it by incident.

I'm so happy that you are able to use this for your own project. Using a ESP to send the the results over WiFi is a great idea!

I have corrected the Power label. Nice catch. You are also correct on the mismatch between the schematics. That is also fixed. Thanks for the feedback!
